#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build CKI Submission Package v48 (Nature Communications).

v48 = v47.3 content + NC format conversion (2026-09-17):
- Manuscript regenerated by generate_manuscript_nc.py (NC structure:
  Introduction / no Conclusions-Keywords-abbreviations / Data+Code
  availability split / Nature-style references / superscript citations /
  lowercase panel labels / Supplementary naming)
- Supplementary Notes by 68_gen_supplementary_nc.py (Notes 1-15 by
  first-citation order; themed sections demoted)
- Guide by 100_gen_reproducibility_nc.js; Cover letter by
  generate_cover_letter_nc.py
- Figures reused from results/figures_v47_author staging; supplementary
  PDFs renamed Supplementary_Fig_N.pdf (in-figure panel labels still
  uppercase by explicit decision -- text layer only this round)

Verification = workers' DOCX self-check scripts (verify_nc_ms.py /
verify_nc_guide.py / check_nc_cl.py) + inline SN checks + package
integrity + scientific regression anchors.
"""
import hashlib
import io
import os
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

BASE = Path(r"C:\Users\KnightZ\Desktop\细胞受选择")
PY = r"C:/Users/KnightZ/AppData/Local/Programs/Python/Python312/python.exe"
NODE = r"C:\Users\KnightZ\.workbuddy\binaries\node\versions\22.22.2-3\node.exe"
NODE_ENV = dict(os.environ, NODE_PATH=r"C:\Users\KnightZ\.workbuddy\binaries\node\workspace\node_modules")

STAGE = BASE / "results" / "figures_v47_author"
FIGS_NC = BASE / "results" / "figures_submission_nc"
WORK_DIR = BASE / "version3" / "CKI_Submission_v48_NC"
ZIP_PATH = BASE / "version3" / "CKI_Submission_v48_NC.zip"
FA = BASE / "_tmp_fa_review"

FAILS = []
PASSES = []


def check(ok, name):
    if ok:
        PASSES.append(name)
        print(f"  [OK] {name}")
    else:
        FAILS.append(name)
        print(f"  [FAIL] {name}")


def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def run(cmd, name, env=None, cwd=None):
    print(f"\n--- {name} ---")
    r = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                       errors="replace", env=env, cwd=cwd or str(BASE))
    tail = "\n".join(r.stdout.splitlines()[-6:])
    print(tail)
    if r.returncode != 0:
        print(r.stderr[-1500:])
    check(r.returncode == 0, f"run: {name}")


def docx_text(p):
    from docx import Document
    return "\n".join(par.text for par in Document(str(p)).paragraphs)


def main():
    print("=" * 60)
    print("  CKI Submission Package v48 (Nature Communications) Builder")
    print("=" * 60)

    # ---- [0] figures staging -> NC naming ----
    print("\n[0] Collecting figures into figures_submission_nc ...")
    FIGS_NC.mkdir(parents=True, exist_ok=True)
    for old in os.listdir(FIGS_NC):
        os.remove(FIGS_NC / old)
    for i in range(1, 7):
        shutil.copy2(STAGE / f"figure{i}.pdf", FIGS_NC / f"figure{i}.pdf")
    for i in range(1, 14):
        shutil.copy2(STAGE / f"figure_S{i}.pdf", FIGS_NC / f"Supplementary_Fig_{i}.pdf")
    for ext in ("pdf", "png", "svg"):
        shutil.copy2(STAGE / f"CKI_graphical_abstract.{ext}",
                     FIGS_NC / f"CKI_graphical_abstract.{ext}")
    n_fig = len(os.listdir(FIGS_NC))
    check(n_fig == 22, f"V48-1 figures staged = 22 (6 main + 13 supp + GA x3) got {n_fig}")

    # ---- [1] work dir ----
    print("\n[1] Preparing CKI_Submission_v48_NC ...")
    if WORK_DIR.exists():
        for old in os.listdir(WORK_DIR):
            os.remove(WORK_DIR / old)
    else:
        WORK_DIR.mkdir(parents=True)
    for f in os.listdir(FIGS_NC):
        shutil.copy2(FIGS_NC / f, WORK_DIR / f)

    # ---- [2] regenerate DOCX ----
    print("\n[2] Regenerating DOCX files ...")
    run([PY, str(BASE / "generate_manuscript_nc.py")], "Generate Manuscript (NC)")
    run([PY, str(BASE / "notebooks" / "68_gen_supplementary_nc.py")], "Generate Supplementary (NC)")
    run([PY, str(BASE / "generate_cover_letter_nc.py")], "Generate Cover Letter (NC)")
    run([NODE, str(BASE / "notebooks" / "100_gen_reproducibility_nc.js")], "Generate Repro Guide (NC)", env=NODE_ENV)

    docx_files = {
        "CKI_Manuscript_NC.docx": BASE / "results" / "CKI_Manuscript_NC.docx",
        "CKI_Supplementary_NC.docx": BASE / "results" / "CKI_Supplementary_NC.docx",
        "CKI_NC_Cover_Letter.docx": BASE / "results" / "CKI_NC_Cover_Letter.docx",
        "CKI_Reproducibility_Guide_NC.docx": BASE / "results" / "CKI_Reproducibility_Guide_NC.docx",
    }
    for name, p in docx_files.items():
        check(p.exists() and p.stat().st_size > 10000, f"DOCX exists: {name}")

    # ---- [2f] fulltext ----
    print("\n[2f] Extracting fulltext ...")
    texts = {}
    for name, p in docx_files.items():
        t = docx_text(p)
        texts[name] = t
        ft = BASE / "results" / (name.replace(".docx", "_fulltext.txt"))
        ft.write_text(t, encoding="utf-8")
        shutil.copy2(ft, WORK_DIR / ft.name)
        print(f"  {ft.name}: {ft.stat().st_size:,} bytes")

    # ---- [3] copy DOCX into workdir + MANIFEST ----
    for name, p in docx_files.items():
        shutil.copy2(p, WORK_DIR / name)

    manifest = ["=" * 60,
                "  CKI Submission Package v48 (Nature Communications)",
                "  MANIFEST_v48.txt",
                "  tag: v0.5.0 | NC format conversion of v47.3",
                "=" * 60, ""]
    entries = sorted(os.listdir(WORK_DIR))
    for i, e in enumerate(entries, 1):
        p = WORK_DIR / e
        manifest.append(f"{i:2d}. {e}  ({p.stat().st_size:,} bytes)")
    manifest.append("")
    manifest.append("SHA-256 checksums:")
    for e in entries:
        manifest.append(f"  {sha256(WORK_DIR / e)}  {e}")
    mtext = "\n".join(manifest) + "\n"
    (WORK_DIR / "MANIFEST_v48.txt").write_text(mtext, encoding="utf-8")

    # ---- [4] zip ----
    print("\n[4] Creating ZIP ...")
    if ZIP_PATH.exists():
        os.remove(ZIP_PATH)
    with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as z:
        for e in sorted(os.listdir(WORK_DIR)):
            z.write(WORK_DIR / e, f"CKI_Submission_v48_NC/{e}")
    main_copy = BASE / "CKI_Submission_v48_NC.zip"
    shutil.copy2(ZIP_PATH, main_copy)
    print(f"  zip: {ZIP_PATH.stat().st_size:,} B ({len(zipfile.ZipFile(ZIP_PATH).namelist())} entries)")

    # ================= VERIFICATION =================
    print("\n" + "=" * 60)
    print("  v48 Verification")
    print("=" * 60)

    ms = texts["CKI_Manuscript_NC.docx"]
    sn = texts["CKI_Supplementary_NC.docx"]
    cl = texts["CKI_NC_Cover_Letter.docx"]
    gd = texts["CKI_Reproducibility_Guide_NC.docx"]

    # ---- workers' DOCX self-check scripts (must exit 0) ----
    run([PY, str(FA / "verify_nc_ms.py")], "verify_nc_ms.py")
    run([PY, str(FA / "verify_nc_guide.py")], "verify_nc_guide.py")
    run([PY, str(FA / "check_nc_cl.py")], "check_nc_cl.py")

    # ---- SN inline checks ----
    print("\n--- SN (inline) ---")
    check(not re.search(r"Note [345]\.\d", sn), "V48-S1 no decimal Note refs in SN")
    check("Fig. S" not in sn and "Figure S" not in sn, "V48-S2 no Fig. S in SN")
    check("Table S" not in sn, "V48-S3 no Table S in SN")
    check("Additional file" not in sn, "V48-S4 no Additional file in SN")
    note_heads = sorted(set(int(m.group(1)) for m in re.finditer(r"Supplementary Note (\d+):", sn)))
    check(note_heads == list(range(1, 16)), f"V48-S5 SN Note headings 1..15 ({note_heads})")
    n_sfig_sn = len(re.findall(r"Supplementary Fig\. \d+", sn))
    check(n_sfig_sn == 7, f"V48-S6 SN Supplementary Fig. refs = 7 ({n_sfig_sn})")
    n_stab_sn = len(re.findall(r"Supplementary Table \d+", sn))
    check(n_stab_sn == 14, f"V48-S7 SN Supplementary Table refs = 14 ({n_stab_sn})")
    check("Supplementary Information" in sn, "V48-S8 SN titled Supplementary Information")

    # ---- Guide inline checks ----
    check("Supplementary Note 13" in gd, "V48-G1 Guide cites Supplementary Note 13")
    check("Section 3.11 of the Supplementary Information" in gd, "V48-G2 Guide Section 3.11 pointer")
    check(not re.search(r"Note [345]\.\d", gd), "V48-G3 no decimal Note refs in Guide")
    check("Fig. S" not in gd and "Table S" not in gd, "V48-G4 no S-naming in Guide")

    # ---- CL inline checks ----
    check(cl.count("Nature Communications") >= 2, "V48-C1 CL names Nature Communications x2+")
    check("Genome Biology" not in cl, "V48-C2 no Genome Biology in CL")
    check("CKI is a Ka/Ks-inspired index quantifying functional divergence in single-cell genomics" in cl,
          "V48-C3 CL carries the NC title")

    # ---- scientific regression anchors (subset of GB build) ----
    print("\n--- scientific anchors ---")
    anchors = [
        ("Strong-candidate count 39", "A1 Strong = 39"),
        ("[7.37, 8.02]", "A2 calibration CI"),
        ("1.74 [1.64, 1.84]", "A3 equal-n gradient"),
        ("0.442", "A4 Augur OvR vs omega"),
        ("0.564", "A5 Augur OvR vs k_f"),
        ("24,413", "A6 Kang cells"),
        ("4,851", "A7 human pairs (phase35)"),
        ("31,764", "A8 brain pairs"),
        ("148.3", "A9 null expectation"),
        ("AUC = 0.80", "A10 AUC"),
        ("6.10-fold", "A11 regional gradient"),
        ("1.3-fold", "A13 ratio bias"),
        ("7.70", "A14 omega baseline"),
        ("10.5281/zenodo.22735744", "A15 Zenodo v0.5.0 DOI"),
        ("GSE96583", "A16 Kang GEO"),
        ("GSE109774", "A17 TCGA/brain GEO in Data availability"),
    ]
    for pat, name in anchors:
        check(pat in ms, f"V48-{name}")
    check("0.953" in sn and "0.951" in sn, "V48-A12 bootstrap-t coverage (SN)")

    # ---- key structural re-checks on fresh text (post-corrections) ----
    print("\n--- structural spot checks ---")
    check("Here, we show" in ms, "V48-SC1 Introduction ends 'Here, we show'")
    h2_long = [t for t in re.findall(r"^(.{61,})$", ms, re.M)
               if t and t[0].isupper() and not t.startswith(("Supplementary", "Additional", "Figure"))]
    # long L2 headings check via docx styles instead (below, cheap proxy: none in MS text lines >=61 that look like headings)
    check(ms.count("Conclusions") == 0, "V48-SC3 no 'Conclusions' anywhere")
    check("Keywords:" not in ms, "V48-SC4 no Keywords line")
    check("Supplementary Note 1" in ms and "Supplementary Note 15" in ms, "V48-SC5 notes 1/15 cited")
    check("Supplementary Fig. 1" in ms, "V48-SC6 supp fig 1 cited")

    # ---- package integrity ----
    print("\n--- package integrity ---")
    names = zipfile.ZipFile(ZIP_PATH).namelist()
    check(all(n.startswith("CKI_Submission_v48_NC/") for n in names), "V48-P1 zip rooted")
    for must in ["CKI_Submission_v48_NC/CKI_Manuscript_NC.docx",
                 "CKI_Submission_v48_NC/CKI_Supplementary_NC.docx",
                 "CKI_Submission_v48_NC/CKI_NC_Cover_Letter.docx",
                 "CKI_Submission_v48_NC/CKI_Reproducibility_Guide_NC.docx",
                 "CKI_Submission_v48_NC/MANIFEST_v48.txt",
                 "CKI_Submission_v48_NC/Supplementary_Fig_1.pdf",
                 "CKI_Submission_v48_NC/Supplementary_Fig_13.pdf",
                 "CKI_Submission_v48_NC/figure1.pdf",
                 "CKI_Submission_v48_NC/figure6.pdf",
                 "CKI_Submission_v48_NC/CKI_graphical_abstract.pdf"]:
        check(must in names, f"V48-P2 {must.split('/')[-1]}")
    n_oldname = [n for n in names if "figure_S" in n or "Supplementary_Figure_S" in n]
    check(not n_oldname, f"V48-P3 no old supp figure naming ({n_oldname})")

    print("\n" + "=" * 60)
    print(f"  Passed: {len(PASSES)}  Failed: {len(FAILS)}")
    for f in FAILS:
        print(f"  [FAIL] {f}")
    if FAILS:
        print("\n  *** FAILURES — review above ***")
        sys.exit(1)
    print("\n  *** ALL CHECKS PASSED — v48 (NC) FINAL ***")


if __name__ == "__main__":
    main()
