"""
#44: Fix phaseB_bootstrap_cis.csv (reviewer fix, v37 review R3-C3)
===================================================================
Problem (v37 review, R3-C3 / R5):
  The committed results/phaseB_bootstrap_cis.csv was generated by
  09_phaseB_statistical_upgrades.py from *legacy* inputs:
    - Brain rows  <- brain_siletti_omega_pairs_v3.csv (old pipeline,
      e.g. Astrocyte omega_mean = 103.08 instead of the manuscript's 76.83)
    - Human rows  <- phase33_v3_human_omega.csv (old 5,151-pair matrix
      instead of the phase35 4,851 analyzed pairs)
    - Human (per-CT) rows <- null_std x 1.96 approximation, which is NOT
      a bootstrap CI (and is referenced nowhere downstream)

Fix:
  1. Recompute the 10 Brain rows from the authoritative block-shuffle
     observed pairs (results/brain_bs_null_observed_pairs.csv, n = 31,764),
     matching the manuscript's per-class statistics.
  2. Recompute the Human (all pairs) row from the authoritative
     results/phase35_all_metrics_pairs.csv (n = 4,851 analyzed pairs).
  3. Drop the 16 pseudo-CI Human (per-CT) rows entirely.
  4. Preserve the Mouse rows VERBATIM from the existing CSV:
       - Mouse (pilot) S_same_ct / D_diff_ct rows feed the manuscript
         loader (_load_manuscript_data.py) and the category CI text.
       - Mouse (pilot) C_control CI [4.24, 9.24] is the calibration-baseline
         CI cited ~9x in the manuscript/supplementary. With a fresh
         RandomState(42) the same estimator yields [4.12, 9.33]; the
         committed [4.24, 9.24] values are kept as the authoritative
         calibration numbers (decision recorded in task #950).
     n_pairs / omega_mean of every preserved row are re-verified against
     the source files so the rows remain fully traceable.

Method (identical to 09_phaseB_statistical_upgrades.py C-S2):
  B = 10,000 bootstrap resamples of the pair-level omega values with
  replacement; CI = 2.5th / 97.5th percentile of the resampled means.
  RandomState(42) freshly seeded per dataset section for determinism.

Usage:
  ./cki_env/Scripts/python.exe notebooks/44_fix_phaseB_cis.py
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _paths import *

import numpy as np
import pandas as pd

B_BOOTSTRAP_CI = 10000
CSV_PATH = RESULTS_DIR / "phaseB_bootstrap_cis.csv"


def bootstrap_ci_mean(values, seed=42):
    """95% percentile bootstrap CI of the mean (B=10,000, with replacement)."""
    rng = np.random.RandomState(seed)
    values = np.asarray(values, dtype=float)
    boot_means = np.array([
        np.mean(rng.choice(values, size=len(values), replace=True))
        for _ in range(B_BOOTSTRAP_CI)
    ])
    return (float(np.percentile(boot_means, 2.5)),
            float(np.percentile(boot_means, 97.5)))


def main():
    # ---- Load current CSV (source of the preserved Mouse rows) ----
    old = pd.read_csv(CSV_PATH)
    mouse_old = old[old["dataset"].str.startswith("Mouse")].copy()
    print(f"Existing CSV: {len(old)} rows; preserving {len(mouse_old)} Mouse rows")

    rows = []

    # ============================================================
    # 1) Brain: authoritative block-shuffle observed pairs
    # ============================================================
    print("\n--- Brain (brain_bs_null_observed_pairs.csv) ---")
    brain = pd.read_csv(RESULTS_DIR / "brain_bs_null_observed_pairs.csv")
    for ct in brain["cell_type"].unique():
        vals = brain.loc[brain["cell_type"] == ct, "omega"].values
        if len(vals) < 5:
            continue
        ci_lo, ci_hi = bootstrap_ci_mean(vals)
        obs_mean = float(np.mean(vals))
        rows.append({
            "dataset": "Brain",
            "group": ct,
            "n_pairs": len(vals),
            "omega_mean": round(obs_mean, 4),
            "ci_95_lower": round(ci_lo, 4),
            "ci_95_upper": round(ci_hi, 4),
            "ci_width": round(ci_hi - ci_lo, 4),
        })
        print(f"  {ct}: n={len(vals)}, omega={obs_mean:.2f} [{ci_lo:.2f}, {ci_hi:.2f}]")

    # ============================================================
    # 2) Human (all pairs): authoritative phase35 analyzed pairs
    # ============================================================
    print("\n--- Human (phase35_all_metrics_pairs.csv) ---")
    human = pd.read_csv(RESULTS_DIR / "phase35_all_metrics_pairs.csv")
    hvals = human["omega"].values
    hvals = hvals[hvals > 0]
    ci_lo, ci_hi = bootstrap_ci_mean(hvals)
    rows.append({
        "dataset": "Human (all pairs)",
        "group": "all",
        "n_pairs": len(hvals),
        "omega_mean": round(float(np.mean(hvals)), 4),
        "ci_95_lower": round(ci_lo, 4),
        "ci_95_upper": round(ci_hi, 4),
        "ci_width": round(ci_hi - ci_lo, 4),
    })
    print(f"  Human all pairs: n={len(hvals)}, omega={np.mean(hvals):.2f} "
          f"[{ci_lo:.2f}, {ci_hi:.2f}]")

    # ============================================================
    # 3) Mouse rows: preserved verbatim, re-verified against sources
    # ============================================================
    print("\n--- Mouse rows (preserved, re-verified) ---")
    # Verify against sources
    v2b = pd.read_csv(RESULTS_DIR / "mouse_pilot_v2b_results.csv")
    mat = pd.read_csv(RESULTS_DIR / "full_matrix_omega.csv", index_col=0)
    mvals = mat.values[np.triu_indices_from(mat.values, k=1)]
    mvals = mvals[mvals > 0]

    ap = mouse_old[mouse_old["dataset"] == "Mouse (all pairs)"].iloc[0]
    assert int(ap["n_pairs"]) == len(mvals), (ap["n_pairs"], len(mvals))
    assert abs(ap["omega_mean"] - float(np.mean(mvals))) < 5e-4

    for cat in ["C_control", "S_same_ct", "D_diff_ct", "X_cross"]:
        r = mouse_old[mouse_old["group"] == cat].iloc[0]
        src = v2b.loc[v2b["category"] == cat, "omega"].values
        assert int(r["n_pairs"]) == len(src), (cat, r["n_pairs"], len(src))
        assert abs(r["omega_mean"] - float(np.mean(src))) < 5e-4, cat
        print(f"  Mouse (pilot) {cat}: n={int(r['n_pairs'])}, "
              f"omega={r['omega_mean']:.4f} "
              f"[{r['ci_95_lower']:.4f}, {r['ci_95_upper']:.4f}]  OK")
    print(f"  Mouse (all pairs): n={int(ap['n_pairs'])}, omega={ap['omega_mean']:.4f} "
          f"[{ap['ci_95_lower']:.4f}, {ap['ci_95_upper']:.4f}]  OK")

    rows.extend(mouse_old.to_dict("records"))

    # ============================================================
    # Write + final verification
    # ============================================================
    out = pd.DataFrame(rows, columns=[
        "dataset", "group", "n_pairs", "omega_mean",
        "ci_95_lower", "ci_95_upper", "ci_width"])
    out.to_csv(CSV_PATH, index=False)
    print(f"\nSaved: {CSV_PATH} ({len(out)} rows)")

    # Sanity checks against manuscript-authoritative values
    astro = out[(out["dataset"] == "Brain") & (out["group"] == "Astrocyte")].iloc[0]
    # Updated 2026-08-30 for corrected extraction (sort_order fix): Astro 76.83 -> 82.748, Bergmann 11.17 -> 13.555
    assert abs(astro["omega_mean"] - 82.748) < 0.01, astro["omega_mean"]
    assert int(astro["n_pairs"]) == 5778
    berg = out[(out["dataset"] == "Brain") & (out["group"] == "Bergmann glia")].iloc[0]
    assert abs(berg["omega_mean"] - 13.555) < 0.01, berg["omega_mean"]
    hum = out[out["dataset"] == "Human (all pairs)"].iloc[0]
    assert int(hum["n_pairs"]) == 4851
    assert abs(hum["omega_mean"] - 21.61) < 0.01, hum["omega_mean"]
    srow = out[out["group"] == "S_same_ct"].iloc[0]
    drow = out[out["group"] == "D_diff_ct"].iloc[0]
    assert abs(srow["ci_95_lower"] - 11.3961) < 1e-6
    assert abs(drow["ci_95_lower"] - 30.0907) < 1e-6
    assert "Human (per-CT)" not in out["dataset"].values
    print("\nAll verification checks passed:")
    print(f"  Brain Astrocyte: omega={astro['omega_mean']} (manuscript 82.748), n={astro['n_pairs']}")
    print(f"  Bergmann glia:   omega={berg['omega_mean']} (manuscript 13.555)")
    print(f"  Human all pairs: n={hum['n_pairs']}, omega={hum['omega_mean']} (manuscript 21.61)")
    print(f"  Mouse S/D CI rows unchanged for loader")
    print(f"  Human (per-CT) pseudo-CI rows removed")


if __name__ == "__main__":
    main()
